inherit_from: ../.rubocop.yml

plugins:
  - rubocop-rspec

Style/ClassAndModuleChildren:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

############################################################
# rubocop-rspec

# believe me, it wasn't by choice
RSpec/AnyInstance:
  Enabled: false

# we meant to do that
RSpec/BeforeAfterAll:
  Enabled: false

# more words != more readable
RSpec/ContextWording:
  Enabled: false

# explicit >>> implicit
RSpec/DescribedClass:
  Enabled: false

# more punctuation != more readable
RSpec/DescribeSymbol:
  Enabled: false

# too late now
RSpec/ExampleLength:
  Enabled: false

# we meant to do that
RSpec/ExpectInHook:
  Enabled: false

# if only it were that simple
RSpec/ExpectOutput:
  Enabled: false

# your naming scheme is not in possession of all the facts
RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/SpecFilePathSuffix:
  Enabled: true

# explicit >>> implicit
RSpec/InstanceVariable:
  Enabled: false

# maybe when 'all' has a corresponding 'none' matcher
RSpec/IteratedExpectation:
  Enabled: false

# TODO: clean these up & de-disable this
RSpec/LeakyConstantDeclaration:
  Enabled: false

# too late now
RSpec/MultipleMemoizedHelpers:
  Enabled: false

# setup cost / time >>> failure granularity
RSpec/MultipleExpectations:
  Enabled: false

# cure is worse than the disease
RSpec/NestedGroups:
  Enabled: false

# more quotation marks != more readable
RSpec/SharedExamples:
  Enabled: false

# we meant to do that
RSpec/StubbedMock:
  Enabled: false

# we meant to do that
RSpec/VerifiedDoubles:
  Enabled: false

RSpec/RemoveConst:
  Enabled: false

############################################################
# rubocop-rspec

# enable newer rubocop-rspec cops

RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: true
